apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-monitoring-app
  template:
    metadata:
      labels:
        app: my-monitoring-app
    spec:
      containers:
      - name: monitoring_app
        image: DOCKER_IMAGE # Specify your Docker image
        ports:
        - containerPort: 80
