name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

env:
  resource_group_name: monitoring_app
  aks_cluster_name: monitoring_app_aks

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      

      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: monitoringappeus.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build Docker image
        run: |
          docker build -t monitoringappeus.azurecr.io/mon_app:latest .
        
      - name: Push Docker image to ACR
        run: |
          docker push monitoringappeus.azurecr.io/mon_app:latest

      - name: Setup Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBS_ID }}
        continue-on-error: true

      - name: Configure Kubernetes context
        run: |
          az aks get-credentials --resource-group $resource_group_name --name $aks_cluster_name

      - name: Update Kubernetes Manifest with Docker Image
        run: |
          sed -i "s|DOCKER_IMAGE|<dockerhub_username>/<image_name>:latest|g" manifests/deployment.yaml

      - name: Deploy to AKS
        run: |
          kubectl apply -f manifests/deployment.yaml
